# Setup
title:               Learn C With Me
description:         'A blog for tutorials on C for beginners and amateurs alike.'
url:                 https://ankan17.github.io
baseurl:             '/learncwithme'

# About/contact
author:
  name:              Ankan Poddar
  email:             apoddar1701@gmail.com
  github_username:   ankan17

# Plugins
plugins:
  - jekyll-paginate

# Collections
collections:

  code_like_pro:
    output: true
    permalink: /:collection/:title/

  crazy_with_c:
    output: true
    permalink: /:collection/:title/

  daily_problems:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: code_like_pro
    values:
      layout: code_like_pro

  - scope:
      path: ""
      type: crazy_with_c
    values:
      title: "Crazy With C"
      layout: crazy_with_c

  - scope:
      path: ""
      type: daily_problems
    values:
      title: "Daily Problems"
      layout: daily_problems


# Sass settings
sass:
  sass_dir:          _sass
  style:             compressed

permalink:           /:title/
paginate:            5
exclude:             ["README.md"]
future:              false
mathjax:             true
mathjax2:            false 
